### ISSUE TITLE
Sever Settings: No reactions when saving server settings with invalid credentials

### ISSUE THREAD

**Issue by dreamagicjp** [movabletype/MovableTypeWriter#16]
## Repro
1. Open 'Server Settings'.
2. Fill in settings with valid Data API endpoint URL and **invalid credentials**
3. Click 'Save' button

## Expected
An error like 'Failed to sign in' occurs.

## Actual
No reactions. I think it's difficult for users to understand if it' saved or not, and why settings are not saved.

**Comment by dreamagicjp** [comment]
I got an error message when saving settings with invalid Data API endpoint URL.

![screenshot 2015-03-02 11 27 28](https://cloud.githubusercontent.com/assets/207862/6434668/a2bb9a76-c0d0-11e4-96a5-e3308dc9504e.png)

**Comment by yuji** [comment]
fixed

**Comment by dreamagicjp** [comment]
Verified!
