### ISSUE TITLE
Server Settings: No reactions when saving settings without any input

### ISSUE THREAD

**Issue by dreamagicjp** [movabletype/MovableTypeWriter#17]
I think it would be nice if we could:

* validate values
* show messages which helps users to correct their mistakes if the validation fails

Currently no messages are displayed if user saves server settings without any input.

![screenshot 2015-03-02 11 39 11](https://cloud.githubusercontent.com/assets/207862/6434701/2153d3ee-c0d1-11e4-80ea-ee7f4de0fb96.png)

**Comment by yuji** [comment]
fixed

**Comment by dreamagicjp** [comment]
Fixed :+1:
