### ISSUE TITLE
Editor: Color picker in rich text editor issues

### ISSUE THREAD

**Issue by dreamagicjp** [movabletype/MovableTypeWriter#18]
Color picker is too tall. User have to scroll to select foreground color.

![screenshot 2015-03-02 12 05 58](https://cloud.githubusercontent.com/assets/207862/6434871/9c5f9304-c0d4-11e4-94e1-41af447bf6db.png)

And should "Set transparent" and "Reset to default" be displayed as buttons?

![screenshot 2015-03-02 12 14 00](https://cloud.githubusercontent.com/assets/207862/6434941/2de5ba00-c0d6-11e4-9f04-23f53d10c05d.png)

**Comment by yuji** [comment]
done

**Comment by dreamagicjp** [comment]
Fixed :+1: 

![screenshot 2015-03-02 17 11 46](https://cloud.githubusercontent.com/assets/207862/6437245/39108f30-c0ff-11e4-91fb-63959abf2b84.png)
