### ISSUE TITLE
Editor: "Reset to default" button does not work in color picker

### ISSUE THREAD

**Issue by dreamagicjp** [movabletype/MovableTypeWriter#19]
## Repro
1. Configure server settings.
2. Open New Entry screen.
3. Type text to entry body
  * and make sure that the text is displayed in black.
4. Set text foreground color to green and type text.
  * and make sure that the text is displayed in green.
5. Click "Reset to default" button for foreground color and type text.
 
## Expected
Foreground color is back to black.

## Actual
Foreground color becomes red. (Why?)

![screenshot 2015-03-02 12 20 45](https://cloud.githubusercontent.com/assets/207862/6434956/907bdb9a-c0d6-11e4-9848-37178304a965.png)

**Comment by yuji** [comment]
hmmm... why these text are mark up with <font> tag...

**Comment by yuji** [comment]
Set milestone to v1.0.1 however, I have no idea to fix this issue now...

**Comment by yuji** [comment]
Turn on 'styleWithSpan' as true! done

**Comment by dreamagicjp** [comment]
Fixed!
