### ISSUE TITLE
Editor: Unable to select "Header 6" style without scrolling the window

### ISSUE THREAD

**Issue by dreamagicjp** [movabletype/MovableTypeWriter#20]
Should the default size of the app window be more larger for usability?

![screenshot 2015-03-02 12 29 38](https://cloud.githubusercontent.com/assets/207862/6435024/028f387a-c0d8-11e4-9889-d3740e4bb46e.png)

**Comment by yuji** [comment]
Change min-height to 700px. done

**Comment by dreamagicjp** [comment]
Fixed :white_check_mark: 

![screenshot 2015-03-02 17 12 40](https://cloud.githubusercontent.com/assets/207862/6437255/63ca563e-c0ff-11e4-9ba1-c8171c6905d0.png)
