### ISSUE TITLE
Editor: Keyboard cursor moves when clicking ordered/unordered button

### ISSUE THREAD

**Issue by dreamagicjp** [movabletype/MovableTypeWriter#21]
If you click the unordered button, the keyboard cursor should move after the bullet. (I tried at http://summernote.org/)

![screenshot 2015-03-02 13 04 13](https://cloud.githubusercontent.com/assets/207862/6435266/2e9248cc-c0dd-11e4-89a4-d71f225074ed.png)

However, the keyboard cursor moves before the bullet

![screenshot 2015-03-02 13 04 55](https://cloud.githubusercontent.com/assets/207862/6435293/49d94cec-c0de-11e4-8503-ad64fa4b93b2.png)

**Comment by yuji** [comment]
hmm... This is a bug by Summer Note... Restriction.

**Comment by dreamagicjp** [comment]
As I commented above, this works well in the demo at http://summernote.org/#/

**Comment by yuji** [comment]
OK, upgrading summernote to 0.6.1. I think this has been fixed.

**Comment by dreamagicjp** [comment]
Fixed :+1: 

![screenshot 2015-03-02 17 10 33](https://cloud.githubusercontent.com/assets/207862/6437241/0d7a29b2-c0ff-11e4-8062-488fb16f8a67.png)
