### ISSUE TITLE
Editor: Unable to expand entry body field to the bottom of the app window

### ISSUE THREAD

**Issue by keiichi4e** [movabletype/MovableTypeWriter#22]
## Repro
1. Open the app
2. Maximize the app window size (If you user OS X Yosemite, click green button)
3. Pull the bar for expanding entry body area to the bottom of the app window

![screenshot 2015-03-02 13 24 11](https://cloud.githubusercontent.com/assets/207862/6435348/0ce404c4-c0e0-11e4-96c8-206cddd3951d.png)

**Comment by yuji** [comment]
Currently, restriction.
