### ISSUE TITLE
Editor: Difficult to understand which category is selected as primary category

### ISSUE THREAD

**Issue by keiichi4e** [movabletype/MovableTypeWriter#23]
There are not differences between primary category and sub categories.

![screenshot 2015-03-02 13 37 52](https://cloud.githubusercontent.com/assets/207862/6435438/5ab1429c-c0e1-11e4-9636-3626c21860b0.png)

MT CMS has UI for it (green star).

![screenshot 2015-03-02 13 40 15](https://cloud.githubusercontent.com/assets/207862/6435450/bb65f038-c0e1-11e4-8493-7e337d175d65.png)

**Comment by yuji** [comment]
Set milestone in v1.0.1, however, I think I can move this case to next milestone if I have no idea to fix this...

**Comment by yuji** [comment]
Move to next milestone
