### ISSUE TITLE
Editor: Upload settings are not respected

### ISSUE THREAD

**Issue by dreamagicjp** [movabletype/MovableTypeWriter#24]
## Repro
1. Open Upload Settings screen
1. Set 'Thumbnail Size' to 'Extra Large (1024px)'
1. Open Create Entry screen
1. Upload this image file (3186px x 1688px)
  * https://cloud.githubusercontent.com/assets/207862/6435918/b20f2d20-c0ea-11e4-992d-6f0074869bc8.png
1. Post

## Expected
The thumbnail width is 1024px.

## Actual
The thumbnail width is 698px. (The thumbnail was displayed as 698px in the editor as well.)

![screenshot 2015-03-02 14 38 05](https://cloud.githubusercontent.com/assets/207862/6435877/fe42f4c0-c0e9-11e4-9c8b-2113970b2c9a.png)

### Entry body of created entry

```html
<p></p>
<p><img src="https://mt6qa3.sixapart.intra/assets_c/2015/03/f01d90f7ea6e1bdd65e4dc31a4b01a1180450c36-thumb-1024xauto-11.png" data-filename="https://mt6qa3.sixapart.intra/assets_c/2015/03/f01d90f7ea6e1bdd65e4dc31a4b01a1180450c36-thumb-1024xauto-11.png" style="width: 698px;" /></p>
<p></p>
```

**Comment by yuji** [comment]
ah.. this is summernote's spec.. I will remove extra large size.

**Comment by yuji** [comment]
done, in the future, i will rethink about this.

**Comment by dreamagicjp** [comment]
Extra Large is not available now.

![screenshot 2015-03-02 17 09 24](https://cloud.githubusercontent.com/assets/207862/6437229/e8c387f8-c0fe-11e4-80a8-2f0c5768febb.png)
