### ISSUE TITLE
Editor: Category list is not rendered when blog has nested categories

### ISSUE THREAD

**Issue by dreamagicjp** [movabletype/MovableTypeWriter#26]
## Pre-req
Create 5-level-nested categories in MT:

![screenshot 2015-03-02 15 04 05](https://cloud.githubusercontent.com/assets/207862/6436108/7de61326-c0ed-11e4-87d9-d14622cf7b68.png)

## Repro
1. Open the app.
1. Open Create Entry screen.
1. Select a blog where you created categories.

## Expected
Category list of the blog is displayed.

## Actual
Category list of the blog is not displayed even if you wait a little while.

![screenshot 2015-03-02 15 03 54](https://cloud.githubusercontent.com/assets/207862/6436133/d6005602-c0ed-11e4-91ef-3d49065d11ca.png)

## Notes
Category list shows up correctly if category list is flattened or low-nested.

**Comment by yuji** [comment]
Fixed

**Comment by dreamagicjp** [comment]
@yuji `[ ]` is displayed under the category list on my environment. Can you reproduce this?

![screenshot 2015-03-02 17 07 41](https://cloud.githubusercontent.com/assets/207862/6437222/ad05dee6-c0fe-11e4-846f-743b97267a80.png)

**Comment by yuji** [comment]
oops. just a debug code..

**Comment by dreamagicjp** [comment]
Fixed :white_check_mark:
