### ISSUE TITLE
Editor: Entry is post always using text formatting settings of MT's Compose Settings

### ISSUE THREAD

**Issue by dreamagicjp** [movabletype/MovableTypeWriter#27]
## Pre-req
1. Open mt.cgi.
2. Open Compose Settings screen.
3. Set 'Markdown' to text formatting.

## Repro
1. Open the app.
2. Post an entry.
3. Open mt.cgi and see the entry on Edit Entry screen.

## Expected
Entry's text format is none. Or richtext?

## Actual
Entry's text format is markdown.

![screenshot 2015-03-02 15 41 06](https://cloud.githubusercontent.com/assets/207862/6436434/9600e030-c0f2-11e4-9992-dfec6e2d1023.png)

**Comment by yuji** [comment]
Always using richtext as text format. done

**Comment by dreamagicjp** [comment]
Fixed :white_check_mark:
