### ISSUE TITLE
Difficult to understand where I am (Create Entry screen or Edit Entry screen)

### ISSUE THREAD

**Issue by keiichi4e** [movabletype/MovableTypeWriter#28]
I think it's difficult for user to know it's Create Entry screen or Edit Entry screen just by taking a look at the screen.

![screenshot 2015-03-02 16 03 20](https://cloud.githubusercontent.com/assets/207862/6436597/d6082a78-c0f5-11e4-8556-1b1aee96695a.png)

I think it would be nice if something like screen title is on the screen.

![screenshot 2015-03-02 16 06 10](https://cloud.githubusercontent.com/assets/207862/6436606/1bce62b6-c0f6-11e4-81b2-ae448d16e308.png)

**Comment by yuji** [comment]
I think we can re-think about UI at next milestone. Don't you?

**Comment by dreamagicjp** [comment]
Yes, sure.
