### ISSUE TITLE
Editor: Position of 'New Entry' button

### ISSUE THREAD

**Issue by keiichi4e** [movabletype/MovableTypeWriter#29]
Edit Entry screen has 'New' button (green button) which opens Create Entry screen:

![screenshot 2015-03-02 16 08 26](https://cloud.githubusercontent.com/assets/207862/6436649/ba3581fa-c0f6-11e4-8825-ea212b9d986c.png)

I think this kind of button (link; moving another page) should not be displayed along with the buttons for page actions such as 'Update' or 'Save'.

**Comment by dreamagicjp** [comment]
How about moving the button to the header area like this?

![screenshot 2015-03-02 16 08 26 copy](https://cloud.githubusercontent.com/assets/207862/6436735/c79de5b6-c0f7-11e4-89c5-998a9f8208d1.png)

**Comment by yuji** [comment]
In this time, difficult to move. Move to next milestone.
